# Generated by Django 3.2 on 2023-02-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
