# Generated by Django 4.0 on 2023-02-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_config', '0003_rename_text_adminpage_body_adminpage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpage',
            name='image',
            field=models.ImageField(upload_to='KB_Admin_logo'),
        ),
    ]
