# Generated by Django 4.0 on 2023-02-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_config', '0004_alter_adminpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpage',
            name='colour',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
