# Generated by Django 4.0 on 2023-02-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_config', '0007_visitorcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorcount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
