# Generated by Django 4.0 on 2023-03-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_config', '0008_visitorcount_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorcount',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visitorcount',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visitorcount',
            name='role',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='visitorcount',
            name='time_of_visit',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
