FROM node:16-alpine

WORKDIR /app

COPY package.json package.json
COPY yarn.lock yarn.lock
COPY . .

ENV PORT=4000
ENV REACT_APP_API_URL=http://localhost:8000/

RUN yarn install 
RUN yarn build

EXPOSE 4000

CMD ["yarn", "start"]