# Generated by Django 4.0 on 2023-02-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=100, null=True, verbose_name='role'),
        ),
    ]
