# Generated by Django 4.0 on 2023-03-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dummy_password',
            field=models.CharField(max_length=300, null=True, verbose_name='dummy_password'),
        ),
    ]
